# Generated by Django 5.2 on 2025-04-23 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_job_user_alter_job_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="posted_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
